name: Documentation Request
description: Create a documented version of a provided file!
title: "[Documentation Request]"
labels: ["doc_request"]
assignees:
  - catdawg-bot
body:
  - type: markdown
    attributes:
      value: |
        Please enter in the details of your request!

  - type: input
    id: url
    attributes:
      label: URL for Analysis
      description: enter in the url file you want documented
      placeholder: ex. https://github.com/TheBradKaiser/catdawg/blob/testbranch/cnn_scrape.py
    validations:
      required: true
