name: PR Review
description: Review a PR on Github!
title: "[PR Review]"
labels: ["pr_review"]
assignees:
  - catdawg-bot
body:
  - type: markdown
    attributes:
      value: |
        Please enter in the details of your request!

  - type: input
    id: url
    attributes:
      label: URL for pull request
      description: enter in the url to the pull request you want reviewed
      placeholder: ex. https://github.com/psf/requests/pull/6960
    validations:
      required: true