name: Tests generator
description: Create a set of tests for a file!
title: "[Tests Request]"
labels: ["test_generator"]
assignees:
  - catdawg-bot
body:
  - type: markdown
    attributes:
      value: |
        Please enter in the details of your request!

  - type: input
    id: url
    attributes:
      label: URL of File for test generation
      description: enter in the url file you want tests created for
      placeholder: ex. https://github.com/TheBradKaiser/catdawg/blob/testbranch/cnn_scrape.py
    validations:
      required: true
